Abstract types, GaussLeastSquares functionality, test cases, and script to automatically get test files + run them
numoptim/OptimizationMethods.jl pull request #3
Opened 2024-09-25 16:04 UTC by VChristian

On this branch, the following things are implemented: 

1. In `src/problems/gaussian_least_squares.jl` three structs are defined: `GaussianLeastSquares`, `PrecomputeGLS`, `AllocateGLS`
2. In `src/problems/gaussian_least_squares.jl` three groups of functions are defined that implement objective, gradient, and hessian evaluations for the least squares problem
3. In `test/problems/proc_gaussian_least_squares.jl` test cases are developed for each of the structs and the functions
4. In `getTests.sh`, a short bash script that finds all `.jl` files in `test` and writes it to a text file is provided
5. In `test/runtests.sh`, a short julia script is provided to run all tests found by `getTests.sh`

2024-10-03 16:39 UTC, vp314 commented
I think item 4 is no longer needed on the PR. Correct?

2024-10-03 16:45 UTC, vp314 requested changes

2024-10-03 16:45 UTC, vp314 commented on test/getTests.sh
I think this file needs to be removed

2024-10-03 17:59 UTC, VChristian commented
> I think item 4 is no longer needed on the PR. Correct?
> 
> I also recommend adding objgrad! to the API

Took care of item 4.

objgrad! is line 448 in `src/problems/gaussian_least_squares.jl`.

2024-10-24 16:54 UTC, vp314 approved these changes

2024-10-24 16:54 UTC, merged